name: Build and Deploy

on:
  push:
    branches:
      - master  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # or your desired version

    - name: Install dependencies and build frontend
      run: |
        cd server
        npm ci

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'capstone-test'
        slot-name: 'production' # Optional. Default is 'production'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_AF2695848D4549EB85D88C6A465BC66B }}
        package: './server'
